services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ./data:/config
      - /your_drive/media/shows:/tv #optional
      - /your_drive/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped