services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - AUTO_UPDATE=true #optional
    volumes:
      - ./data:/config
      - /your_drive/media/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
