services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - JELLYFIN_PublishedServerUrl=
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ./config:/config
      - /your_drive/media/shows:/data/shows
      - /your_drive/media/movies:/data/movies
      - /your_drive/media/music:/data/music
      - /your_drive/media/music videos:/data/music videos
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    restart: unless-stopped
